stages:
- name: gobuild
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        mkdir -p /go/src/github.com/vipidp
        ln -s `pwd` /go/src/github.com/vipidp/example
        cd /go/src/github.com/vipidp/example/outyet
        go build -o bin/outyet
        ls bin/outyet
- name: gotest
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        mkdir -p /go/src/github.com/vipidp
        ln -s `pwd` /go/src/github.com/vipidp/example
        cd /go/src/github.com/vipidp/example/outyet
        go test
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./outyet/Dockerfile
      buildContext: .
      tag: test/gohello:latest
      pushRemote: true
      registry: hub.birucloud.com
timeout: 60
