FROM golang:alpine
MAINTAINER birucloud-golang-demo
#RUN apk add --update curl bash && \
#    rm -rf /var/cache/apk/*
WORKDIR $GOPATH/src/app/
COPY . $GOPATH/src/app/
EXPOSE 8080
#ENTRYPOINT ["./outyet"]
